name: onspace
description: OnSpace interview assessment project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  custom_map_markers: ^0.0.2+1
  custom_marker: ^1.0.0
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_animated_dialog: ^2.0.1
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_debouncer: ^2.0.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.4
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^12.1.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  location: ^5.0.3
  page_transition: ^2.1.0
  shimmer: ^3.0.0

dev_dependencies:
  bloc_test: ^9.1.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
  build_runner: 2.4.7
  json_serializable: 6.7.1


flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Spline
      fonts:
        - asset: assets/fonts/SplineSans-Bold.ttf
        - asset: assets/fonts/SplineSans-Light.ttf
        - asset: assets/fonts/SplineSans-Medium.ttf
        - asset: assets/fonts/SplineSans-Regular.ttf
        - asset: assets/fonts/SplineSans-SemiBold.ttf
