name: onspace

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false

#  flutter_test:
#    name: Run Flutter Test And Analyze
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#      - uses: subosito/flutter-action@v1
#        with:
#          flutter-version: '2.5.0'
#          channel: 'stable'
#      - run: flutter pub get
#      - run: flutter test

#  build_appbundle:
#    name: Build Flutter (Android)
#    needs: [flutter_test]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v2
#        with:
#          distribution: 'zulu'
#          java-version: '11'
#      - uses: subosito/flutter-action@v2
#        with:
#          channel: "stable"
#      - run: flutter pub get
#      - run: flutter clean
#      - run: flutter build apk --debug --split-per-abi
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}

